name: Fetch Open PRs with Specific Label

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '*/5 * * * *'  # Runs every day at 9 AM UTC

jobs:
  fetch_open_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Open Pull Requests with Label
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEEBHOOK }}
        id: get_open_prs
        run: |
          LABEL="test"
          OPEN_PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&per_page=100")

          FILTERED_PRS=$(echo "$OPEN_PRS" | jq --arg LABEL "$LABEL" '[.[] | select(.labels[]? | .name == $LABEL)]')

          echo "$FILTERED_PRS" > filtered_prs.json

          PR_COUNT=$(echo "$FILTERED_PRS" | jq '. | length')
          echo "Total Open PRs with label '$LABEL': $PR_COUNT"

          echo "$FILTERED_PRS" | jq -r '.[] | "Title: \(.title), URL: \(.html_url), Author: \(.user.login), Created At: \(.created_at)"'
          MESSAGE = "$FILTERED_PRS" | jq -r '.[] | "Title: \(.title), URL: \(.html_url), Author: \(.user.login), Created At: \(.created_at)"'
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" "${{ secrets.SLACK_WEEBHOOK }}"
