name: Post Ruby Output to Slack

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Ruby Script
        id: run_script
        run: |
          output=$(bundle exec test_ruby.rb)
          echo "::set-output name=script_output::$output"

      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
           {
            "text": "Ruby Script Output:\n${{ steps.run_script.outputs.script_output }}"
           }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEEBHOOK }}
